export const CSRF_LOG_EVENTS = {
  CSRF_TOKEN_CONTENT_INVALID: "CSRF_TOKEN_CONTENT_INVALID",
  CSRF_TOKEN_GENERATED: "CSRF_TOKEN_GENERATED",
  CSRF_TOKEN_INVALID: "CSRF_TOKEN_INVALID",
  CSRF_TOKEN_INVALID_REUSE: "CSRF_TOKEN_INVALID_REUSE",
  CSRF_TOKEN_MISSING: "CSRF_TOKEN_MISSING",
  REQUEST_CONTENT_INVALID: "REQUEST_CONTENT_INVALID",
} as const;
