# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Lint, and Test

on:
  push:
    branches: [ "main", "v[0-9].x.x" ]
  pull_request:
    branches: [ "main", "v[0-9].x.x" ]

permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        
      - name: Run Biome
        run: biome ci

  test:
    name: Run Test Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    
    - name: Install Node Dependencies
      run: npm ci
  
    - name: Build
      run: npm run build --if-present
  
    - name: Run Test Coverage
      run: npm run test:coverage